"""empty message

Revision ID: 8b879a00084d
Revises: 072fe8dc1a72
Create Date: 2025-11-29 03:13:12.849923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b879a00084d'
down_revision = '072fe8dc1a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starship_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorite_starship_starship_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'starship', ['starship_id'], ['id'])
        batch_op.drop_column('starship')

    with op.batch_alter_table('favorite_vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorite_vehicle_vehicle_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])
        batch_op.drop_column('vehicle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_vehicle_vehicle_fkey', 'vehicle', ['vehicle'], ['id'])
        batch_op.drop_column('vehicle_id')

    with op.batch_alter_table('favorite_starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starship', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_starship_starship_fkey', 'starship', ['starship'], ['id'])
        batch_op.drop_column('starship_id')

    # ### end Alembic commands ###
